name: my_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  file_picker: ^10.2.0
  lottie: ^3.3.1
  fl_chart: ^1.0.0
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  device _info_plus: ^10.1.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/logo.png
    - assets/animations/uploading.json
    - assets/animations/success.json
    - assets/animations/error.json
    - assets/animations/success-2.json
    - assets/avatars/
    - assets/easteregg/skeleton.png
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
